language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "knorrke-github"
  token:
    secure: ${SONAR_TOKEN}
    
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install jacoco:report sonar:sonar

after_success:
  - mvn coveralls:report
