language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: 
  - mvn clean test cobertura:cobertura -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Djava.awt.headless=true -Dtestfx.setup.timeout=2500
after_success:
  - mvn coveralls:report
